#!/bin/sh

pipe_pwd=`pwd`
pipe_postfix=${pipe_pwd//\//_}
pipe_path="/tmp/.vipe_pipe_${pipe_postfix}"

test -p $pipe_path || mkfifo $pipe_path
trap "rm -f $pipe_path" EXIT

echo "\x1b[35mRunning bash pipe in ${pipe_path}\x1b[0m"

while true; do
  if read line < $pipe_path; then
    if [[ "$line" == 'quit' ]]; then
        break
    fi
    eval "clear"
    eval "time $line"
  fi
done
