#!/usr/bin/env ruby

Dir.chdir(ARGV.pop || '.')
TAG_FILE = ENV['TAG_FILE'] || 'tags'
paths = %w[ . ]
File.exists?('Gemfile') && paths += `bundle list --paths`.lines.map(&:chomp)
cmd = File.exists?('/usr/local/bin/ctags') ? %w[ /usr/local/bin/ctags -f ] : %w[ ctags -f ]
cmd << TAG_FILE
cmd += %w[ --recurse=yes --languages=Ruby,C ]
cmd += paths
$DEBUG and warn "Executing #{cmd * ' '}."
system *cmd
megabytes = File.size(TAG_FILE).to_f / 1024 ** 2 rescue nil
megabytes and warn "Created %.3fM of tags for #{TAG_FILE}." % megabytes
