#!/bin/bash
# Utility to update a host dotfiles installation to the latest version.
# Usage: `dotfiles-up`

export DOTFILES_UP_START_DIR=`pwd`
cd $DOTFILES_HOME
git stash
git pull origin master
git stash pop
# Initialize git submodules which may have been added
git submodule init
git submodule update
cd $DOTFILES_UP_START_DIR
source $DOTFILES_SHELL_CONFIG
