#!/bin/bash
# Utility to update a host dotfiles installation to the latest version.
# Usage: `dotfiles-up`

pushd
cd $DOTFILES_HOME
git stash
git pull origin master
git stash pop
# Initialize git submodules which may have been added
git submodule init
git submodule update
popd
source $DOTFILES_SHELL_CONFIG
