#!/usr/bin/env ruby
#
# Usage: github-pull repository/name
#
# 1) switches to ENV['DEV_HOME']
# 2) checks out the github repository
# 3) cds into the repository

DEV_HOME  = ENV.fetch('DEV_HOME')
REPO_ID   = ARGV.first or raise ArgumentError, 'Missing arg: repository/path'
REPO_NAME = REPO_ID.split('/').last
REPO_PATH = "#{DEV_HOME}/#{REPO_NAME}"

unless File.exists? REPO_PATH
  exec "git clone git@github.com:#{REPO_ID}.git"
  puts "Repo checkout out to #{REPO_PATH}"
else
  puts "Repo already checkout out to #{REPO_PATH}"
end
puts "Switch to it by using 'scm #{REPO_NAME}'"
