#!/bin/bash
OLD_MAC=`ifconfig en1|grep ether`
NEW_MAC=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'`

echo Disconnecting..
sudo airport -z
echo Waiting 10 seconds before changing the MAC address
sleep 10
echo Changing old MAC $OLD_MAC to new MAC $NEW_MAC
sudo ifconfig en0 ether $NEW_MAC
