#!/bin/bash 
DBUSER=$MYSQL_USER_ROOT
DBPASS=$MYSQL_USER_ROOT_PASSWD
DUMPDIR=./DB_DUMPS

DUMPDATE=$(date '+%Y-%m-%d')

if [ ! -d $DUMPDIR ] ; then
mkdir $DUMPDIR
fi

for IDX in $(echo "show databases;" |mysql --user=$DBUSER --password=$DBPASS -s)
do
mysqldump --user=$DBUSER --password=$DBPASS --databases $IDX > $DUMPDIR/${IDX}_${DUMPDATE}.sql
done

