#!/usr/bin/env ruby
require 'FileUtils'
require 'pathname'

home_dir = Dir.home
latex_template_dir = "#{home_dir}/.vim/templates/latex"

# create template dir if not exists
if !File.directory? latex_template_dir then
  puts "creating template dir: #{latex_template_dir}"
  FileUtils.mkdir_p latex_template_dir
  puts "now put in some template files"
  exit
end

latex_templates    = Dir[latex_template_dir + "/*.tex"]
latex_plugin_dir   = "#{home_dir}/.vim/bundle/vim-latex"

puts "found #{latex_templates.length} template files to link"

# create symlinks for templates
latex_templates.each do |template|
  file_name   = Pathname.new(template).basename.to_s
  target_path = latex_plugin_dir + "/ftplugin/latex-suite/templates/" + file_name
  puts "linking the latex template '#{file_name}' to #{target_path}"
  %x[sudo ln -s #{template} #{target_path}]
end

