#!/usr/bin/env ruby


git_bundles = {
  #"git://github.com/astashov/vim-ruby-debugger.git",
  #"git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/nerdtree.git" => nil,
  #"git://github.com/timcharper/textile.vim.git",
  #"git://github.com/tpope/vim-cucumber.git",
  #"git://github.com/tpope/vim-fugitive.git",
  #"git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git" => nil,
  "git://github.com/tpope/vim-markdown.git" => nil,
  "git://github.com/tpope/vim-rails.git" => nil,
  #"git://github.com/tpope/vim-repeat.git",
  #"git://github.com/tpope/vim-surround.git",
  #"git://github.com/tpope/vim-vividchalk.git",
  #"git://github.com/tsaleh/vim-align.git",
  #"git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-supertab.git" => nil,
  "git://github.com/tsaleh/vim-tcomment.git" => nil,
  #"git://github.com/vim-ruby/vim-ruby.git",
  #"git://github.com/mirosr/vim-irblack.git" => nil,
  "git://github.com/mineiro/vim-latex.git" => nil,
  "git://github.com/tpope/vim-unimpaired.git" => nil,
  "git://github.com/kchmck/vim-coffee-script.git" => nil,
  "git://github.com/bronson/vim-runtest.git" => nil,
  "git://github.com/mileszs/ack.vim.git" => nil,
  "git://github.com/wincent/Command-T.git" => "rvm use system; cd Command-T/ruby/command-t/; ruby extconf.rb; make; sudo make install",
  "git://github.com/vim-scripts/taglist.vim.git" => nil,
  #"git://github.com/vim-scripts/Color-Sampler-Pack.git"
  "git://github.com/grekko/vim-jellybeans-grekko.git" => nil,
  "git://github.com/grekko/vim-irblack-grekko.git" => nil,
  "git://github.com/mileszs/ack.vim.git" => nil
}


vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  #["gist",          "12732", "plugin"],
  ["jquery",        "12107", "syntax"],
]


require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url, cmd|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))

  unless cmd == nil then
    puts "executing hook for bundle"
    system "#{cmd}"
  end
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
