#!/usr/bin/env ruby


git_bundles = {
  "git://github.com/tsaleh/vim-supertab.git" => nil,
  "git://github.com/vim-scripts/tComment.git" => nil,
  "git://github.com/mineiro/vim-latex.git" => nil,
  #"git://github.com/wincent/Command-T.git" => "rvm use system; cd Command-T/ruby/command-t/; ruby extconf.rb; make; sudo make install",
  "git://github.com/vim-scripts/taglist.vim.git" => nil,
  "git://github.com/grekko/vim-jellybeans-grekko.git" => nil,
  "git://github.com/grekko/vim-irblack-grekko.git" => nil,
  "git://github.com/vim-scripts/FuzzyFinder.git" => nil,
  "git://github.com/vim-scripts/L9.git" => nil,
  "git://github.com/vim-scripts/zoom.vim.git" => nil,
  # "git://github.com/vim-scripts/upAndDown.git" => nil,
  "git://github.com/taxilian/VimDebugger.git" => nil,
  "git://github.com/sunaku/vim-ruby-minitest.git" => "mv vim-ruby-minitest/after after"
}


vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  #["gist",          "12732", "plugin"],
  ["jquery",        "12107", "syntax"],
]


require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")
FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url, cmd|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))

  unless cmd == nil then
    puts "executing hook for bundle"
    system "#{cmd}"
  end
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
