" Basics
set nocompatible                             " choose no compatibility with legacy vi
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Bundle 'altercation/vim-colors-solarized'
Bundle 'AKurilin/matchit.vim'
Bundle 'Keithbsmiley/rspec.vim'
Bundle 'Lokaltog/vim-distinguished'
Bundle 'SirVer/ultisnips'
Bundle 'Yggdroot/indentLine'
Bundle 'bkad/CamelCaseMotion'
Bundle 'ecomba/vim-ruby-refactoring'
Bundle 'endel/vim-github-colorscheme'
Bundle 'ervandew/supertab'
Bundle 'gmarik/vundle'
Bundle 'grekko/vimux'
Bundle 'jakar/vim-json'
Bundle 'kana/vim-textobj-user'
Bundle 'kchmck/vim-coffee-script'
Bundle 'kien/ctrlp.vim'
Bundle 'lukaszb/vim-web-indent'
Bundle 'mattn/gist-vim'
Bundle 'mattn/webapi-vim'
Bundle 'mileszs/ack.vim'
Bundle 'mineiro/vim-latex'
Bundle 'rhysd/vim-textobj-ruby'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'sjl/vitality.vim'
Bundle 'skalnik/vim-vroom'
Bundle 'slim-template/vim-slim'
Bundle 'tpope/vim-bundler'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'vim-ruby/vim-ruby'
Bundle 'vim-scripts/Align'
Bundle 'vim-scripts/IndexedSearch'
Bundle 'vim-scripts/L9'
Bundle 'vim-scripts/YankRing.vim'
Bundle 'vim-scripts/tComment'
Bundle 'vim-scripts/zoom.vim'

filetype plugin indent on                    " Turns on filetype detection, filetype plugins, and filetype indenting
                                             " all of which add nice extra features to whatever language you're using
if has("syntax")
  syntax on
end

set nocursorcolumn
set cursorline
syntax sync minlines=256

set autoindent                               " automatic indentation after newline
set autowriteall                             " http://vim.wikia.com/wiki/Auto_save_files_when_focus_is_lost
set backspace=2
set backupdir=~/.vim/backup
set directory=~/.vim/backup
set encoding=utf-8                           " Set encoding
set expandtab
set foldmethod=manual                        " Folding settings
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set list listchars=tab:\ \ ,trail:·
set matchpairs+=<:> " http://vim.1045645.n5.nabble.com/Highlighting-matching-angle-brackets-lt-gt-td1188629.html
set nowrap                                   " dont wrap lines
set number                                   " show line numbers
set pastetoggle=<F2>
set relativenumber
set ruler
set scrolloff=5
set shell=bash                               "set shell=/usr/local/bin/zsh\ --interactive
set shiftwidth=2
set showcmd
set sidescroll=1
set sidescrolloff=5
set smartcase
set softtabstop=2
set statusline=File:\ %F\ Line:\ %4l/%L/%P\ %3b
set synmaxcol=128
set tabstop=2
set tags=tags;/
set textwidth=200
set title
set ttyfast

let mapleader = ","                          " Set mapleader

" http://vim.wikia.com/wiki/Auto_save_files_when_focus_is_lost
au FocusLost * :wa


" Visual
set background=dark
" colorscheme solarized
colorscheme distinguished
set guifont=Meslo\ LG\ M\ DZ\ for\ Powerline:h12
highlight Pmenu    ctermfg=87  ctermbg=238 guifg=Lightgreen guibg=grey10
highlight PmenuSel ctermfg=237 ctermbg=255 guibg=DarkGrey


" Syntastic
let g:syntastic_quiet_warning = 0
let g:syntastic_ruby_checkers = ['mri', 'rubocop']
let g:syntastic_mode_map = { 'mode': 'passive' }

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_enable_balloons = 0
let g:syntastic_check_on_open = 1
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'

nnoremap <leader>ss :SyntasticCheck<CR>


" Syntastic Colors
highlight SyntasticErrorSign   ctermfg=124 ctermbg=0 guifg=#af0000 guibg=black
highlight SyntasticErrorLine   ctermfg=124 ctermbg=0 guifg=#af0000 guibg=black
highlight SyntasticWarningSign ctermfg=64  ctermbg=0 guifg=#5f5f00 guibg=black


" indentLine
let g:indentLine_color_term = 239
let g:indentLine_char = '┊'


if exists('+colorcolumn')
  set colorcolumn=120
endif


" Yankring
nnoremap <silent> <F11> :YRShow<CR>


" CamelCaseMotion
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
sunmap w
sunmap b
sunmap e


" Gist
let g:gist_detect_filetype = 1
let g:gist_clip_command = 'pbcopy'


" Ack
nnoremap <leader>ff :Ack 


" Rails
nnoremap <leader>fc :Econtroller 
nnoremap <leader>fv :Eview 
nnoremap <leader>fm :Emodel 
nnoremap <leader>as :AS<CR>
nnoremap <leader>av :AV<CR>


" Replace visually selected word with last deleted/yanked text
" http://vim.wikia.com/wiki/Replace_a_word_with_yanked_text
" vnoremap S "_dP


" nowrap toggle
map <F2> :set nowrap!<CR>


" powerline
" https://powerline.readthedocs.org/en/latest/overview.html#installation
set rtp+=/usr/local/lib/python2.7/site-packages/powerline/bindings/vim


" spell check
map <F3> :setlocal spell spelllang=de_de<CR>
map <F4> :set nospell<CR>


" TComment
map <C-C> :TComment<cr>


" Configure navigation keys
cnoremap <C-h>   <Left>
cnoremap <C-l>   <Right>
cnoremap <C-k>   <Up>
cnoremap <C-j>   <Down>


" Splits
nnoremap <leader>sv :vsplit<CR>
nnoremap <leader>sh :split<CR>
" http://robots.thoughtbot.com/post/48275867281/vim-splits-move-faster-and-more-naturally
set splitbelow
set splitright


" UltiSnips
let g:UltiSnipsExpandTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories = ["my-ultisnips"]


" copy paste
vnoremap <leader>cop "*y


" save of file
nnoremap SS :w<CR>
nnoremap ZX :w<CR>:SyntasticCheck<CR>


" syntax toggle
function! ToggleSyntax()
  if g:syntaxon == 1
    syntax off
    let g:syntaxon = 0
  else
    syntax on
    let g:syntaxon = 1
  endif
endfunction

let g:syntaxon = 1
nnoremap <F6> :call ToggleSyntax()<CR>


" Stamping
" http://vim.wikia.com/wiki/Replace_a_word_with_yanked_text
" nnoremap S diw"0P


" CtrlP
let g:ctrlp_show_hidden = 1

nnoremap <leader>pp :CtrlP<CR>
nnoremap <leader>pm :CtrlPBufTag<CR>

let g:ctrlp_custom_ignore = {
      \'dir':  '\.git$\|\.hg$\|\.svn$\|\.yardoc$\|vendor\/bundle$\|tmp$',
      \'file': '\.sassc$\|\.exe$\|\.so$\|\.dat$'
      \}


" Align
vnoremap <leader>a :Align =<CR>


" Ruby Refactoring
" Default Bindings
" nnoremap <leader>rap  :RAddParameter<cr>
" nnoremap <leader>rcpc :RConvertPostConditional<cr>
" nnoremap <leader>rel  :RExtractLet<cr>
" vnoremap <leader>rec  :RExtractConstant<cr>
" vnoremap <leader>relv :RExtractLocalVariable<cr>
" nnoremap <leader>rit  :RInlineTemp<cr>
" vnoremap <leader>rrlv :RRenameLocalVariable<cr>
" vnoremap <leader>rriv :RRenameInstanceVariable<cr>
" vnoremap <leader>rem  :RExtractMethod<cr>
" (r)eplace (h)ash(r)ocket
nnoremap <leader>rhr :%s/:\([^ ]*\)\(\s*\)=>/\1:/gc<CR>

" function! RefactoringRename()
  " let l:newname = input("New name? ")
  " call :%s//l:newname/g<CR>
" endfunction
" nnoremap <leader>ren :call RefactoringRename()<CR>
" nmap <leader>ren :call RefactoringRename()<CR>


" Fugitive
nnoremap <leader>go :Gbrowse<CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gw :Gwrite<CR>
nnoremap <leader>gc :Gcommit<CR>


" Custom commands / productivity
nnoremap <leader>gpp :!git pp<CR>
" Fast escape of insert mode: http://learnvimscriptthehardway.stevelosh.com/chapters/10.html
inoremap jk <esc>
inoremap jk <esc>


" Barbaric Mode: Force yourself not using esc in insert mode..

function! BarbaricModeOn()
  inoremap <esc> <nop>
  nnoremap <Up>    <Nop>
  nnoremap <Down>  <Nop>
  nnoremap <Left>  <Nop>
  nnoremap <Right> <Nop>
endfunc

function! BarbaricModeOff()
  inoremap <esc> <esc>
  nnoremap <Up>  <up>
  nnoremap <Down> <down>
  nnoremap <Left>  <left>
  nnoremap <Right> <right>
endfunc

function! BarbaricModeToggle()
  if g:barabaric_mode == 1
    call BarbaricModeOff()
    let g:barabaric_mode = 0
    echo 'Turned barbaric mode OFF: You can use the arrow keys again champ.'
  else
    let g:barabaric_mode = 1
    call BarbaricModeOn()
    echo 'Turned barbaric mode ON: You are on your own now..'
  endif
endfunc
nnoremap <F7> :call BarbaricModeToggle()<CR>

let g:barabaric_mode = 1
call BarbaricModeOn()


" vroom
let g:vroom_use_vimux = 1
let g:vroom_map_keys  = 0
let g:vroom_use_bundle_exec = 0
let g:vroom_spec_command = 'rspec --drb'


" Vimux
nnoremap <leader>tmr :VimuxPromptCommand<CR>
let g:VimuxUseExistingPaneWithIndex = 1

map <leader>sf :VroomRunTestFile<CR>
map <leader>sc :VroomRunNearestTest<CR>


" Ruby Text Objects
" https://github.com/rhysd/vim-textobj-ruby
" let g:textobj_ruby_more_mappings = 1


" NERDTree
let NERDTreeShowHidden = 1
" Doesnt work right now
" let NERDTreeStatusline = ""
nnoremap <leader>ntt :NERDTreeToggle<CR>
nnoremap <leader>ntr :NERDTreeFind<CR>

" autocmd hooks
if has("autocmd")
  " au VimEnter * NERDTree | wincmd p

  augroup ruby
    au!
  augroup END

  augroup CursorLine
    "au!
    "au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
    "au WinLeave * setlocal nocursorline
  augroup END
end



" Thorfile, Rakefile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Thorfile,config.ru} set ft=ruby


" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Allow saving of files as sudo when I forgot to start vim using sudo.
" http://stackoverflow.com/questions/2600783/how-does-the-vim-write-with-sudo-trick-work
cnoremap w!! %!sudo tee > /dev/null %
